import assert from 'node:assert/strict';
import {createServer} from 'vite';
const values=new Map();
globalThis.window={localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},dispatchEvent:()=>{}};
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try {
 const {mockProviders:p}=await server.ssrLoadModule('/src/providers/mock/mockProviders.ts');
 const {hospitalAccounts}=await server.ssrLoadModule('/src/data/mockData.ts');
 const {getMockState}=await server.ssrLoadModule('/src/services/mockStore.ts');
 for(const a of hospitalAccounts) assert.equal((await p.auth.login(a.email,a.password)).hospital.id,a.hospitalId);
 const a=hospitalAccounts[0];await p.auth.login(a.email,a.password);const id=a.hospitalId;
 await assert.rejects(p.resource.getResources('HSP-002'),/Access denied/);
 const before=await p.resource.getResources(id);
 const beds={general:{total:120,occupied:86},icu:{total:10,occupied:3},emergency:{total:20,occupied:4}};
 const saved=await p.resource.updateBeds(id,beds);assert.equal(saved.beds.general.available,34);
 await assert.rejects(p.resource.updateBeds(id,{...beds,general:{total:1,occupied:2}}));
 await assert.rejects(p.resource.updateBeds(id,{...beds,general:{total:-1,occupied:0}}));
 let r=await p.resource.createDoctor(id,{name:'Dr. Aditi Shah',department:'Emergency',specialization:'Emergency Medicine',status:'AVAILABLE'});
 const d=r.doctors.at(-1);assert.equal(d.hospitalId,id);
 r=await p.resource.updateDoctor(id,d.id,{...d,name:'Dr. Aditi Shah Updated',status:'OFF_DUTY'});assert.equal(r.doctors.at(-1).status,'OFF_DUTY');
 await p.resource.deleteDoctor(id,d.id);assert.equal((await p.resource.getResources(id)).doctors.length,before.doctors.length);
 r=await p.resource.createAmbulance(id,{vehicleNumber:'MH-04-AB-4821',driverName:'Ramesh Patil',status:'AVAILABLE'});const ambulance=r.ambulances.at(-1);
 r=await p.resource.updateAmbulance(id,ambulance.id,{...ambulance,status:'MAINTENANCE'});assert.equal(r.ambulances.at(-1).status,'MAINTENANCE');
 await p.resource.updateAmbulance(id,ambulance.id,{...ambulance,status:'AVAILABLE'});
 const pending=await p.emergency.getNew(id);assert(pending.length);const e=await p.emergency.accept(pending[0].id,id);
 await p.resource.assignAmbulance(e.id,id,ambulance.id);await assert.rejects(p.resource.deleteAmbulance(id,ambulance.id),/active case/);
 for(const status of ['EN_ROUTE','PATIENT_PICKED_UP','ARRIVED','COMPLETED']) await p.emergency.updateStatus(e.id,id,status);
 assert.equal((await p.resource.getResources(id)).ambulances.at(-1).status,'AVAILABLE');
 await p.resource.deleteAmbulance(id,ambulance.id);
 const input={hospitalName:'Test Hospital',licenseNumber:'TEST-001',hospitalType:'Private',address:'Demo address',city:'Mumbai',state:'Maharashtra',pinCode:'400001',emergencyPhone:'0000000000',hospitalEmail:'hospital@example.test',adminName:'Test Admin',designation:'Admin',adminEmail:'admin@example.test',adminPhone:'0000000000',password:'MockOnly123!',generalBeds:10,icuBeds:2,emergencyBeds:3,ambulanceCount:1};
 const record=await p.auth.register(input);assert.equal(record.status,'APPROVED');assert.equal(record.hospitalId,'HSP-005');assert(!('password' in record));assert(!JSON.stringify(getMockState()).includes(input.password));
 await assert.rejects(p.auth.login(input.adminEmail,'WrongPassword!'),/incorrect/);
 assert.equal((await p.auth.login(input.adminEmail,input.password)).hospital.id,record.hospitalId);
 const newResources=await p.resource.getResources(record.hospitalId);assert.deepEqual(newResources.beds,{general:{total:0,occupied:0,available:0},icu:{total:0,occupied:0,available:0},emergency:{total:0,occupied:0,available:0}});assert.equal(newResources.doctors.length,0);assert.equal(newResources.ambulances.length,0);
 assert.equal((await p.emergency.getNew(record.hospitalId)).length,0);assert.equal((await p.emergency.getOngoing(record.hospitalId)).length,0);
 await assert.rejects(p.resource.getResources(id),/Access denied/);
 await p.resource.updateBeds(record.hospitalId,{general:{total:12,occupied:2},icu:{total:3,occupied:0},emergency:{total:4,occupied:1}});
 await p.resource.createDoctor(record.hospitalId,{name:'Dr. New Tenant',department:'Emergency',specialization:'Emergency Medicine',status:'AVAILABLE'});
 p.auth.logout();assert.equal((await p.auth.login(input.adminEmail,input.password)).hospital.id,record.hospitalId);assert.equal((await p.resource.getResources(record.hospitalId)).doctors.length,1);
 const secondInput={...input,hospitalName:'Second Hospital',licenseNumber:'TEST-002',hospitalEmail:'hospital2@example.test',adminEmail:'admin2@example.test'};
 const secondRecord=await p.auth.register(secondInput);assert.equal(secondRecord.hospitalId,'HSP-006');assert.notEqual(secondRecord.hospitalId,record.hospitalId);
 await assert.rejects(p.auth.register(input),/already registered/);
 await assert.rejects(p.auth.register({...secondInput,licenseNumber:'TEST-003',adminEmail:'admin3@example.test',hospitalEmail:input.adminEmail}),/already registered/);
 const persisted=JSON.parse(values.get('lifelink-demo-operational-state-v3'));assert.equal(persisted.resources[id].beds.general.available,34);assert.equal(persisted.registrations.length,2);assert.equal(persisted.hospitals.length,6);assert.equal(persisted.accounts.length,2);assert(!JSON.stringify(persisted).includes(input.password));
 server.moduleGraph.invalidateAll();
 const reloaded=await server.ssrLoadModule("/src/services/mockStore.ts");const {mockProviders:reloadedProviders}=await server.ssrLoadModule('/src/providers/mock/mockProviders.ts');assert.equal(reloaded.getMockState().resources[id].beds.general.available,34);assert.equal(reloaded.getMockState().registrations.length,2);assert.equal((await reloadedProviders.auth.login(input.adminEmail,input.password)).hospital.id,record.hospitalId);assert.equal((await reloadedProviders.resource.getResources(record.hospitalId)).beds.general.available,10);
 await reloadedProviders.demo.reset();assert.equal(reloaded.getMockState().registrations.length,0);assert.equal(reloaded.getMockState().accounts.length,0);assert.equal(reloaded.getMockState().hospitals.length,4);assert.equal(reloadedProviders.auth.getSession(),null);
 assert.equal((await reloadedProviders.auth.login(a.email,a.password)).hospital.id,id);assert.equal((await reloadedProviders.resource.getResources(id)).doctors.length,before.doctors.length);
 reloadedProviders.auth.logout();await assert.rejects(reloadedProviders.resource.getResources(id),/Access denied/);
 console.log('PASS: four demo logins, auto-active registration, sequential hospital IDs, hashed credential persistence, immediate/repeat login, wrong-password and duplicate rejection, empty new tenant state, tenant isolation, resource editing, refresh persistence, emergency lifecycle/release, and demo reset.');
} finally {await server.close();}
