import assert from 'node:assert/strict';
import {createServer} from 'vite';
const values=new Map();
globalThis.window={localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},dispatchEvent:()=>{}};
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try {
 const {mockProviders:p}=await server.ssrLoadModule('/src/providers/mock/mockProviders.ts');
 const {hospitalAccounts}=await server.ssrLoadModule('/src/data/mockData.ts');
 const {getMockState}=await server.ssrLoadModule('/src/services/mockStore.ts');
 for(const a of hospitalAccounts) assert.equal((await p.auth.login(a.email,a.password)).hospital.id,a.hospitalId);
 const a=hospitalAccounts[0];await p.auth.login(a.email,a.password);const id=a.hospitalId;
 await assert.rejects(p.resource.getResources('HSP-002'),/Access denied/);
 const before=await p.resource.getResources(id);
 const beds={general:{total:120,occupied:86},icu:{total:10,occupied:3},emergency:{total:20,occupied:4}};
 const saved=await p.resource.updateBeds(id,beds);assert.equal(saved.beds.general.available,34);
 await assert.rejects(p.resource.updateBeds(id,{...beds,general:{total:1,occupied:2}}));
 await assert.rejects(p.resource.updateBeds(id,{...beds,general:{total:-1,occupied:0}}));
 let r=await p.resource.createDoctor(id,{name:'Dr. Aditi Shah',department:'Emergency',specialization:'Emergency Medicine',status:'AVAILABLE'});
 const d=r.doctors.at(-1);assert.equal(d.hospitalId,id);
 r=await p.resource.updateDoctor(id,d.id,{...d,name:'Dr. Aditi Shah Updated',status:'OFF_DUTY'});assert.equal(r.doctors.at(-1).status,'OFF_DUTY');
 await p.resource.deleteDoctor(id,d.id);assert.equal((await p.resource.getResources(id)).doctors.length,before.doctors.length);
 r=await p.resource.createAmbulance(id,{vehicleNumber:'MH-04-AB-4821',driverName:'Ramesh Patil',status:'AVAILABLE'});const ambulance=r.ambulances.at(-1);
 r=await p.resource.updateAmbulance(id,ambulance.id,{...ambulance,status:'MAINTENANCE'});assert.equal(r.ambulances.at(-1).status,'MAINTENANCE');
 await p.resource.updateAmbulance(id,ambulance.id,{...ambulance,status:'AVAILABLE'});
 const pending=await p.emergency.getNew(id);assert(pending.length);const e=await p.emergency.accept(pending[0].id,id);
 await p.resource.assignAmbulance(e.id,id,ambulance.id);await assert.rejects(p.resource.deleteAmbulance(id,ambulance.id),/active case/);
 for(const status of ['EN_ROUTE','PATIENT_PICKED_UP','ARRIVED','COMPLETED']) await p.emergency.updateStatus(e.id,id,status);
 assert.equal((await p.resource.getResources(id)).ambulances.at(-1).status,'AVAILABLE');
 await p.resource.deleteAmbulance(id,ambulance.id);
 const input={hospitalName:'Test Hospital',licenseNumber:'TEST-001',hospitalType:'Private',address:'Demo address',city:'Mumbai',state:'Maharashtra',pinCode:'400001',emergencyPhone:'0000000000',hospitalEmail:'hospital@example.test',adminName:'Test Admin',designation:'Admin',adminEmail:'admin@example.test',adminPhone:'0000000000',password:'MockOnly123!',generalBeds:10,icuBeds:2,emergencyBeds:3,ambulanceCount:0};
 const record=await p.auth.register(input);assert.equal(record.status,'PENDING_APPROVAL');assert(!('password' in record));assert(!JSON.stringify(getMockState()).includes(input.password));
 await assert.rejects(p.auth.register(input),/already registered/);
 await assert.rejects(p.auth.login(input.adminEmail,input.password));
 const persisted=JSON.parse(values.get('lifelink-demo-operational-state-v3'));assert.equal(persisted.resources[id].beds.general.available,34);assert.equal(persisted.registrations.length,1);
 server.moduleGraph.invalidateAll();
 const reloaded=await server.ssrLoadModule("/src/services/mockStore.ts");assert.equal(reloaded.getMockState().resources[id].beds.general.available,34);assert.equal(reloaded.getMockState().registrations.length,1);
 await p.demo.reset();assert.equal(getMockState().registrations.length,0);assert.equal((await p.resource.getResources(id)).doctors.length,before.doctors.length);
 p.auth.logout();await assert.rejects(p.resource.getResources(id),/Access denied/);
 console.log('PASS: four demo logins, tenant isolation, bed validation/calculation, doctor CRUD, ambulance CRUD, active-case protection, emergency lifecycle/release, pending registration, no password persistence, duplicate rejection, persisted state, demo reset.');
} finally {await server.close();}
