import { CheckCircle2 } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { registrationService } from '../services/registrationService';
import type { HospitalRegistrationInput, HospitalRegistration as Registration } from '../types';
import { isMockMode } from '../config/runtime';
export function HospitalRegistration() {
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<Registration|null>(null);
 async function submit(e: FormEvent<HTMLFormElement>) {
  e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setError('');
  if(f.get('password')!==f.get('confirmPassword')) {setError('Passwords do not match.');return;}
  const p=Object.fromEntries(f.entries()) as unknown as HospitalRegistrationInput;
  delete (p as unknown as Record<string, unknown>).confirmPassword;
  for(const k of ['generalBeds','icuBeds','emergencyBeds','ambulanceCount'] as const) p[k]=Number(f.get(k));
  for(const k of ['latitude','longitude'] as const) p[k]=f.get(k) ? Number(f.get(k)) : undefined;
  setBusy(true);try {const record=await registrationService.register(p);form.reset();setResult(record);}catch(e){setError(e instanceof Error ? e.message : 'Unable to submit registration.');}finally{setBusy(false);}
 }
 function field(label:string,name:string,type='text',required=true) {return <label key={name}>{label}{!required && ' (optional)'}<input name={name} type={type} required={required} minLength={type==='password'?8:undefined} autoComplete={type==='password'?'new-password':undefined} pattern={name==='pinCode'?'[0-9]{6}':undefined} step={type==='number'?'any':undefined}/></label>;}
 if(result) return <main className="registration-page"><section className="resource-table-card registration-success"><CheckCircle2 size={46} aria-hidden="true"/><span className="eyebrow">Join LifeLink</span><h1>Request submitted successfully</h1>{isMockMode ? <><p role="status"><strong>{result.hospitalName}</strong> has been added to the LifeLink network and can now log in.</p><p>Your hospital ID is <strong>{result.hospitalId}</strong>. Use the administrator email and password entered during signup.</p><p>Your new workspace starts with zero resources and no emergencies, ready for your hospital team to update.</p></> : <><p role="status">{result.status.replaceAll('_',' ')}</p><p>Your hospital application has been received. Access will follow the backend's configured onboarding workflow.</p></>}<p>Application reference: {result.id}</p><Link className="button button--primary" to="/login">Go to Login</Link></section></main>;
 return <main className="registration-page"><Link className="text-link" to="/login">← Back to hospital login</Link><header className="page-header page-header--compact"><div><span className="eyebrow">Hospital partner application</span><h1>Join LifeLink</h1><p>Register your hospital with the LifeLink network.</p></div></header><form className="management-form resource-table-card" onSubmit={submit}><fieldset disabled={busy} className="editor-fields"><fieldset><legend>Hospital information</legend><div className="editor-grid">{field('Hospital name','hospitalName')}{field('Registration / license number','licenseNumber')}<label>Hospital type<select name="hospitalType" required><option value="">Select type</option><option>Government</option><option>Private</option><option>Charitable</option><option>Other</option></select></label>{field('Address','address')}{field('City','city')}{field('State','state')}{field('PIN code','pinCode')}{field('Emergency contact number','emergencyPhone','tel')}{field('Official hospital email','hospitalEmail','email')}{field('Website','website','url',false)}{field('Latitude','latitude','number',false)}{field('Longitude','longitude','number',false)}</div></fieldset><fieldset><legend>Administrator information</legend><div className="editor-grid">{field('Admin full name','adminName')}{field('Designation','designation')}{field('Admin email','adminEmail','email')}{field('Admin phone','adminPhone','tel')}{field('Password (at least 8 characters)','password','password')}{field('Confirm password','confirmPassword','password')}</div></fieldset><fieldset><legend>Initial capacity</legend><p>Enter separate bed categories; general beds exclude ICU and emergency beds. In Mock Mode, the operational workspace starts at zero so staff can confirm and enter current resources after login.</p><div className="editor-grid">{[['generalBeds','General beds'],['icuBeds','ICU beds'],['emergencyBeds','Emergency beds'],['ambulanceCount','Ambulances']].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" step="1" required defaultValue="0"/></label>)}</div></fieldset></fieldset>{isMockMode && <p>Prototype mode: registration creates a browser-local hospital account immediately. Use fictional contact details.</p>}{error && <p role="alert" className="login-error">{error}</p>}<button className="button button--primary" disabled={busy}>{busy?'Submitting…':'Register hospital'}</button></form></main>;
}
