import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { registrationService } from '../services/registrationService';
import type { HospitalRegistrationInput, HospitalRegistration as Registration } from '../types';
import { isMockMode } from '../config/runtime';
export function HospitalRegistration() {
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<Registration|null>(null);
 async function submit(e: FormEvent<HTMLFormElement>) {
  e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setError('');
  if(f.get('password')!==f.get('confirmPassword')) {setError('Passwords do not match.');return;}
  const p=Object.fromEntries(f.entries()) as unknown as HospitalRegistrationInput;
  delete (p as unknown as Record<string, unknown>).confirmPassword;
  for(const k of ['generalBeds','icuBeds','emergencyBeds','ambulanceCount'] as const) p[k]=Number(f.get(k));
  for(const k of ['latitude','longitude'] as const) p[k]=f.get(k) ? Number(f.get(k)) : undefined;
  setBusy(true);try {const record=await registrationService.register(p);form.reset();setResult(record);}catch(e){setError(e instanceof Error ? e.message : 'Unable to submit registration.');}finally{setBusy(false);}
 }
 function field(label:string,name:string,type='text',required=true) {return <label key={name}>{label}{!required && ' (optional)'}<input name={name} type={type} required={required} minLength={type==='password'?8:undefined} autoComplete={type==='password'?'new-password':undefined} pattern={name==='pinCode'?'[0-9]{6}':undefined} step={type==='number'?'any':undefined}/></label>;}
 if(result) return <main className="registration-page"><section className="resource-table-card"><span className="eyebrow">Join LifeLink</span><h1>Registration submitted</h1><p role="status">{result.status.replaceAll('_',' ')}</p><p>Your hospital application has been received and is awaiting verification. Emergency access requires approval.</p><p>Application reference: {result.id}</p>{isMockMode && <p>This demo application is saved on this browser. It does not create a login or send a verification request.</p>}<Link className="button button--primary" to="/login">Back to login</Link></section></main>;
 return <main className="registration-page"><Link className="text-link" to="/login">← Back to hospital login</Link><header className="page-header page-header--compact"><div><span className="eyebrow">Hospital partner application</span><h1>Join LifeLink</h1><p>Register your hospital for verification.</p></div></header><form className="management-form resource-table-card" onSubmit={submit}><fieldset disabled={busy} className="editor-fields"><fieldset><legend>Hospital information</legend><div className="editor-grid">{field('Hospital name','hospitalName')}{field('Registration / license number','licenseNumber')}<label>Hospital type<select name="hospitalType" required><option value="">Select type</option><option>Government</option><option>Private</option><option>Charitable</option><option>Other</option></select></label>{field('Address','address')}{field('City','city')}{field('State','state')}{field('PIN code','pinCode')}{field('Emergency contact number','emergencyPhone','tel')}{field('Official hospital email','hospitalEmail','email')}{field('Website','website','url',false)}{field('Latitude','latitude','number',false)}{field('Longitude','longitude','number',false)}</div></fieldset><fieldset><legend>Administrator information</legend><div className="editor-grid">{field('Admin full name','adminName')}{field('Designation','designation')}{field('Admin email','adminEmail','email')}{field('Admin phone','adminPhone','tel')}{field('Password (at least 8 characters)','password','password')}{field('Confirm password','confirmPassword','password')}</div></fieldset><fieldset><legend>Initial capacity</legend><p>Enter separate bed categories; general beds exclude ICU and emergency beds. Names and availability can be added after approval.</p><div className="editor-grid">{[['generalBeds','General beds'],['icuBeds','ICU beds'],['emergencyBeds','Emergency beds'],['ambulanceCount','Ambulances']].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" step="1" required defaultValue="0"/></label>)}</div></fieldset></fieldset>{isMockMode && <p>Demo only: use fictional contact details. Passwords are validated but are not saved.</p>}{error && <p role="alert" className="login-error">{error}</p>}<button className="button button--primary" disabled={busy}>{busy?'Submitting…':'Submit for approval'}</button></form></main>;
}
