import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { ErrorState } from '../components/ui/ErrorState';
import { resourceService } from '../services/resourceService';
import { ResourceEditor, type Editor } from '../components/resources/ResourceEditor';
import type { HospitalResourceSummary } from '../types';
export function Resources() {
 const {currentHospital} = useAuth(); const [data,setData] = useState<HospitalResourceSummary|null>(null);
 const [error,setError] = useState(''); const [retry,setRetry] = useState(0); const [editor,setEditor] = useState<Editor|null>(null); const [success,setSuccess] = useState('');
 useEffect(() => { let active = true; setData(null);setError(''); if(currentHospital) resourceService.getResources(currentHospital.id).then(r => {if(active)setData(r);}).catch(e => {if(active)setError(e.message);});return()=>{active=false;}; },[currentHospital,retry]);
 if(error) return <div className="page"><ErrorState message={error} onRetry={()=>setRetry(n=>n+1)}/></div>;
 if(!currentHospital || !data) return <div className="page loading-state">Loading hospital resources…</div>;
 const emergencyDoctors = data.doctors.filter(d=>/emergency/i.test(`${d.department} ${d.specialization}`));
 return <div className="page resources-page"><header className="page-header page-header--compact"><div><span className="eyebrow">{currentHospital.id} · Hospital capacity</span><h1>Resources</h1><p>Private operational availability for {currentHospital.name}.</p><small>Last updated: {new Date(data.updatedAt).toLocaleString()}</small></div><div className="connection-pill"><span/>Scoped to this hospital</div></header>
 {success && <p role="status">{success}</p>}
 <div className="resource-page-grid resource-page-grid--four"><article className="resource-page-card"><strong>{data.ambulances.filter(a=>a.status === "AVAILABLE").length} / {data.ambulances.length}</strong><h2>Ambulances available</h2><p>Dispatch-ready vehicles in this hospital’s fleet.</p><button className="button" onClick={()=>setEditor({kind:"ambulance"})}>Add ambulance</button></article>{(['general','icu','emergency'] as const).map(k=><article className="resource-page-card" key={k}><strong>{data.beds[k].available} / {data.beds[k].total}</strong><h2>{k === 'icu' ? 'ICU' : k[0].toUpperCase()+k.slice(1)} beds</h2><p>{data.beds[k].occupied} occupied · {data.beds[k].available} available</p><button className="button" onClick={()=>setEditor({kind:'beds'})}>Edit beds</button></article>)}<article className="resource-page-card"><strong>{emergencyDoctors.filter(d=>d.status==='AVAILABLE').length}</strong><h2>Emergency doctors available</h2><p>{data.doctors.filter(d=>d.status==='AVAILABLE').length} available across all departments</p><button className="button" onClick={()=>setEditor({kind:'doctor'})}>Add doctor</button></article></div>
 <section className="resource-detail-grid"><article className="resource-table-card"><div className="section-heading"><div><span className="eyebrow">{data.ambulances.filter(a=>a.status==='AVAILABLE').length} available / {data.ambulances.length} total</span><h2>Ambulances</h2></div><button className="button" onClick={()=>setEditor({kind:'ambulance'})}>Add ambulance</button></div><div className="resource-list">{!data.ambulances.length && <p>No ambulances added yet</p>}{data.ambulances.map(a=><div className="resource-list-row" key={a.id}><div><strong>{a.vehicleNumber}</strong><span>Driver: {a.driverName || 'Not assigned'}{a.driverPhone && ` · ${a.driverPhone}`}</span><span className={`resource-status resource-status--${a.status.toLowerCase()}`}>{a.status.replaceAll('_',' ')}</span></div><div className="resource-actions"><button className="button" onClick={()=>setEditor({kind:'ambulance',id:a.id})}>Edit</button><button className="button" aria-label={`Remove ${a.vehicleNumber}`} onClick={()=>setEditor({kind:'ambulance',id:a.id,remove:true})}>Remove</button></div></div>)}</div></article>
 <article className="resource-table-card resource-table-card--ivory"><div className="section-heading"><div><span className="eyebrow">Clinical team</span><h2>Doctors</h2></div><button className="button" onClick={()=>setEditor({kind:'doctor'})}>Add doctor</button></div><div className="resource-list">{!data.doctors.length && <p>No doctors added yet</p>}{data.doctors.map(d=><div className="resource-list-row" key={d.id}><div><strong>{d.name}</strong><span>{[d.department,d.specialization,d.phone].filter(Boolean).join(' · ')}</span><span className={`resource-status resource-status--${d.status.toLowerCase()}`}>{d.status.replaceAll('_',' ')} · {d.currentCases} active cases</span></div><div className="resource-actions"><button className="button" onClick={()=>setEditor({kind:'doctor',id:d.id})}>Edit</button><button className="button" aria-label={`Remove ${d.name}`} onClick={()=>setEditor({kind:'doctor',id:d.id,remove:true})}>Remove</button></div></div>)}</div></article></section>
 {editor && <ResourceEditor editor={editor} data={data} onClose={()=>setEditor(null)} onSaved={r=>{setData(r);setEditor(null);setSuccess('Hospital resources updated.');}}/>}</div>;
}
